
#1-Generate a sample by equation


> *y=w1X1+w2X2+....+b*





#2-Generate random number for Xs

#3-Apply Linear Regression

#4-Proof the same equatio will return using generated sample datasets



#Apply that Algorithm for 1 D , 2 D hyper plain


Note: This code can be used as 1D or 2D (hyper plain) according to the input of the user in ['Enter number of xs: ']

In [ ]:
#importing for needed libraries
import numpy as np
import random as rd

#getting important data from the user & handling errors
n = int(input("Enter number of xs: "))
while(n!=1 and n!=2):
  print("Error! Enter 1 or 2! Try again!")
  n = int(input("Enter number of xs: "))

x_length = int(input("Enter the length of xs: "))
while(x_length < 1):
  print("Error! Enter valid length! Try again!")
  x_length = int(input("Enter the length of xs: "))

#preparing variables
ones = [1] * x_length
x = [0] * x_length
y = [0] * x_length
i = 0
needed_list=[]
needed_matrix=[]

#applying 1D or 2D (hyper plain) according to user's input
if (n == 1): 
  print("1D:")
elif (n == 2):
  print("2D (hyper plain):")

while(i<n):
  print("x%i:"%(i+1))
  #getting a
  a = float(input("Enter a: "))
  needed_list.append(a)
  #putting x
  for j in range(x_length):
    x[j] = rd.random()
  #getting x matrix
  needed_matrix.append(x.copy()) 
  y = [m + a * n for m, n in zip(y, x)]
  i+=1
#putting ones columns
needed_matrix.append(ones)
#getting b
b = float(input("Enter b: "))
#getting w
needed_list.append(b)
b_list = [b] * x_length
#getting y
y = [l + k for l, k in zip(y, b_list)]

Enter number of xs: 2
Enter the length of xs: 10
2D (hyper plain):
x1:
Enter a: 5
x2:
Enter a: 9
Enter b: 4


In [ ]:
#Showing original x matrix
x_new = np.transpose(needed_matrix)
print("Original x matrix")
print(x_new)

Original x matrix
[[0.72849054 0.70218172 1.        ]
 [0.6075797  0.84588869 1.        ]
 [0.73517114 0.09163467 1.        ]
 [0.45159471 0.97377937 1.        ]
 [0.43970647 0.16186938 1.        ]
 [0.16511584 0.93013426 1.        ]
 [0.9293519  0.6492666  1.        ]
 [0.13095485 0.50653031 1.        ]
 [0.71564024 0.96295213 1.        ]
 [0.67983261 0.23096278 1.        ]]


In [ ]:
#Showing original y vector
print("Original y:")
y_vector = []
y_vector.append(y.copy())
y_vector = np.transpose(y_vector)
print(y_vector)

Original y:
[[13.96208818]
 [14.6508967 ]
 [ 8.50056772]
 [15.02198792]
 [ 7.65535675]
 [13.19678756]
 [14.49015892]
 [ 9.21354703]
 [16.2447704 ]
 [ 9.47782808]]


In [ ]:
#Showing original w vector
print("Original w:")
w_vector = []
w_vector.append(needed_list.copy())
w_vector = np.transpose(w_vector)
print(w_vector)

Original w:
[[5.]
 [9.]
 [4.]]


In [ ]:
#getting new y
random_list = [0] * x_length
for k in range(x_length):
    random_list[k] = rd.random()
y_new = [n1 + n2 for n1, n2 in zip(y, random_list)]

In [ ]:
#Showing new y vector
print("New y:")
y_new_new = []
y_new_new.append(y_new)
y_new_new = np.transpose(y_new_new)
print(y_new_new)

New y:
[[14.32112457]
 [15.03580145]
 [ 9.03527741]
 [15.31405806]
 [ 8.00083535]
 [14.00876902]
 [15.23014726]
 [ 9.732656  ]
 [16.69553095]
 [10.36521762]]


In [ ]:
#getting new w vector
ws = np.linalg.inv(x_new.T@x_new)@x_new.T@y_new_new

In [ ]:
#Showing new w vector
print("w output:")
print(ws)

w output:
[[5.00373516]
 [8.88599778]
 [4.59948796]]


##Refrences

https://machinelearningmastery.com/linear-regression-for-machine-learning/

https://towardsdatascience.com/linear-regression-derivation-d362ea3884c2

